<?php 

require "fpdf.php";
session_start();

class myPDF extends FPDF
{
	
	function header()
	{
		$zone = $_SESSION['fname']." ".$_SESSION['lname'];
		$date = date('d-m-Y');
		$this -> Image('report.png', 10, 5, 35, 20);
		$this -> SetFont('Arial', 'B', 14);
		$this -> Cell(30);
		$this -> Cell(154, 5, 'Computer Maintenance Report', 0, 0, 'L');
		$this -> SetFont('Times', '', 12);
		$this -> Cell(85, 5, $date, 0, 0, 'R');
		$this -> Ln();	
		$this -> Cell(30);
		$this -> Cell(150, 7, 'Generated By '.$zone, 0, 0, 'L');$this -> Ln(15);
		$this -> SetFont('Times', 'B', 15);
		$this -> Ln();	
		$this -> Cell(30);
		$this -> Cell(150, 7, 'Please bring this paper with Bank transaction reference number.', 0, 0, 'L');
		$this -> Ln(15);
	}

	function footer(){

		$this -> SetY(-25);
		$this -> SetFont('Times', '', 10);
		$this -> Cell(9);
		$this -> Cell(10, 5, 'CBE :- 1351331188134354           Signature ____________________', 0, 0, 'L');
		$this -> SetY(-15);
		$this -> SetFont('Arial', '', 8);
		$this -> Cell(0,10,'Page '.$this->PageNO().'/{nb}',0,0,'C');
	}

	function headerTable(){
        
		$this -> SetFont('Times', 'B', 12);
		$this -> Cell(10);
		$this -> Cell(20, 8, 'id', 1, 0, 'L');
		$this -> Cell(50, 8, 'device', 1, 0, 'L');
		$this -> Cell(50, 8, 'problem', 1, 0, 'L');
		$this -> Cell(50, 8, 'serial', 1, 0, 'L');
		$this -> Cell(25, 8, 'register', 1, 0, 'L');
		$this -> Cell(25, 8, 'finished', 1, 0, 'L');
		$this -> Ln();

	}

	function viewTable(){
		$this -> SetFont('Times', 'B', 12);
		$db = new PDO('mysql:host=localhost;dbname=maintenance','root','');
          $id = $_SESSION['cid'];

		$stmt = $db->query("SELECT * FROM request WHERE uid='$id'");
       
		while ($data = $stmt -> fetch(PDO::FETCH_OBJ)){
			$this -> Cell(10);
			$this -> Cell(20, 8, $data->rid, 1, 0, 'L');
			$this -> Cell(50, 8, $data->device_name, 1, 0, 'L');
			$this -> Cell(50, 8, $data->problemCS, 1, 0, 'L');
			$this -> Cell(50, 8, $data->serial, 1, 0, 'L');
			$this -> Cell(25, 8, $data->registerd_date, 1, 0, 'L');
			$this -> Cell(25, 8, $data->recive_date, 1, 0, 'L');
			$this -> Ln();
		}
	}
}

	$pdf = new myPDF();
	$pdf -> AliasNbPages();
	$pdf -> AddPage('L', 'A4', 0);
	$pdf -> headerTable();
	$pdf -> viewTable();
	$pdf -> Output();

 ?>