<?php 

require "fpdf.php";
session_start();

class myPDF extends FPDF
{

	function header()
	{
		$name = $_SESSION['name'];
		$date = date('d-m-Y');
		$this -> Image('report.png', 10, 5, 35, 20);
		$this -> SetFont('Arial', 'B', 14);
		$this -> Cell(30);
		$this -> Cell(154, 5, 'Vehicles Registration Report', 0, 0, 'L');
		$this -> SetFont('Times', '', 12);
		$this -> Cell(85, 5, $date, 0, 0, 'R');
		$this -> Ln();	
		$this -> Cell(30);
		$this -> Cell(150, 7, 'Generated By '.$name, 0, 0, 'L');
		$this -> Ln(15);
	}

	function footer(){

		$this -> SetY(-25);
		$this -> SetFont('Times', '', 10);
		$this -> Cell(9);
		$this -> Cell(10, 5, 'Approved by ______________________           Signature ____________________', 0, 0, 'L');
		$this -> SetY(-15);
		$this -> SetFont('Arial', '', 8);
		$this -> Cell(0,10,'Page '.$this->PageNO().'/{nb}',0,0,'C');
	}

	function headerTable(){

		$this -> SetFont('Times', 'B', 10);
		$this -> Cell(10);
		$this -> Cell(40, 8, 'chassis', 1, 0, 'L');
		$this -> Cell(10, 8, 'code', 1, 0, 'L');
		$this -> Cell(15, 8, 'plate', 1, 0, 'L');
		$this -> Cell(20, 8, 'region', 1, 0, 'L');
		$this -> Cell(25, 8, 'zone', 1, 0, 'L');
		$this -> Cell(20, 8, 'vehicle type', 1, 0, 'L');
		$this -> Cell(15, 8, 'category', 1, 0, 'L');
		$this -> Cell(30, 8, 'manufactured by', 1, 0, 'L');
		$this -> Cell(30, 8, 'owner name', 1, 0, 'L');
		$this -> Cell(30, 8, 'registered by', 1, 0, 'L');
		$this -> Cell(25, 8, 'date', 1, 0, 'L');
		$this -> Ln();

	}

	function viewTable(){
		$this -> SetFont('Times', 'B', 10);
		$db = new PDO('mysql:host=10.198.75.220;dbname=etms','biruk','Software123');

		$f_date =  $_SESSION['from_date'];
		$t_date =  $_SESSION['to_date'];
		$zone = $_SESSION['zone'];

		$stmt = $db->query("SELECT * FROM `vehicle` WHERE `registration_zone` = '$zone' AND `registration_date` BETWEEN '$f_date' AND '$t_date'");

		while ($data = $stmt -> fetch(PDO::FETCH_OBJ)){
			$this -> Cell(10);
			$this -> Cell(40, 8, $data->chassis_no, 1, 0, 'L');
			$this -> Cell(10, 8, $data->code, 1, 0, 'L');
			$this -> Cell(15, 8, $data->plate_no, 1, 0, 'L');
			$this -> Cell(20, 8, $data->region, 1, 0, 'L');
			$this -> Cell(25, 8, $data->registration_zone, 1, 0, 'L');
			$this -> Cell(20, 8, $data->vehicle_type, 1, 0, 'L');
			$this -> Cell(15, 8, $data->category, 1, 0, 'L');
			$this -> Cell(30, 8, $data->manufacture_comp, 1, 0, 'L');

			$stmt2 = $db->query("SELECT * FROM `owner_info` WHERE `owner_id` = '$data->owner_id'");
			$zdata = $stmt2 -> fetch(PDO::FETCH_OBJ);

			$this -> Cell(30, 8, $zdata->first_name." ".$zdata->last_name, 1, 0, 'L');

			$stmt3 = $db->query("SELECT * FROM `user` WHERE `id` = '$zdata->user_id'");
			$udata = $stmt3 -> fetch(PDO::FETCH_OBJ);

			$this -> Cell(30, 8, $udata->fname." ".$udata->lname, 1, 0, 'L');
			$this -> Cell(25, 8, $data->registration_date, 1, 0, 'L');
			$this -> Ln();
		}
	}
}

	$pdf = new myPDF();
	$pdf -> AliasNbPages();
	$pdf -> AddPage('L', 'A4', 0);
	$pdf -> headerTable();
	$pdf -> viewTable();
	$pdf -> Output();

 ?>